global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:

rule_files:

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "client-1"
    static_configs:
    - targets: ["client-1:9141"]

  - job_name: "client-2"
    static_configs:
    - targets: ["client-2:9142"]

  - job_name: "client-3"
    static_configs:
    - targets: ["client-3:9143"]


  - job_name: "peer-1"
    static_configs:
    - targets: ["peer-1:9091"]

  - job_name: "peer-2"
    static_configs:
    - targets: ["peer-2:9092"]

  - job_name: "peer-3"
    static_configs:
    - targets: ["peer-3:9093"]

  - job_name: "peer-4"
    static_configs:
    - targets: ["peer-4:9094"]

  - job_name: "peer-5"
    static_configs:
    - targets: ["peer-5:9095"]

  - job_name: "peer-6"
    static_configs:
    - targets: ["peer-6:9096"]

  - job_name: "peer-7"
    static_configs:
    - targets: ["peer-7:9097"]

  - job_name: "peer-8"
    static_configs:
    - targets: ["peer-8:9098"]

  - job_name: "peer-9"
    static_configs:
    - targets: ["peer-9:9099"]

  - job_name: "peer-10"
    static_configs:
    - targets: ["peer-10:9100"]

  - job_name: "peer-11"
    static_configs:
    - targets: ["peer-11:9101"]

  - job_name: "peer-12"
    static_configs:
    - targets: ["peer-12:9102"]

  - job_name: "peer-13"
    static_configs:
    - targets: ["peer-13:9103"]

  - job_name: "peer-14"
    static_configs:
    - targets: ["peer-14:9104"]

  - job_name: "peer-15"
    static_configs:
    - targets: ["peer-15:9105"]

  - job_name: "peer-16"
    static_configs:
    - targets: ["peer-16:9106"]

  - job_name: "peer-17"
    static_configs:
    - targets: ["peer-17:9107"]

  - job_name: "peer-18"
    static_configs:
    - targets: ["peer-18:9108"]

  - job_name: "peer-19"
    static_configs:
    - targets: ["peer-19:9109"]

  - job_name: "peer-20"
    static_configs:
    - targets: ["peer-20:9110"]

  - job_name: "peer-21"
    static_configs:
    - targets: ["peer-21:9111"]

  - job_name: "peer-22"
    static_configs:
    - targets: ["peer-22:9112"]

  - job_name: "peer-23"
    static_configs:
    - targets: ["peer-23:9113"]

  - job_name: "peer-24"
    static_configs:
    - targets: ["peer-24:9114"]

  - job_name: "peer-25"
    static_configs:
    - targets: ["peer-25:9115"]

  - job_name: "peer-26"
    static_configs:
    - targets: ["peer-26:9116"]

  - job_name: "peer-27"
    static_configs:
    - targets: ["peer-27:9117"]

  - job_name: "peer-28"
    static_configs:
    - targets: ["peer-28:9118"]

  - job_name: "peer-29"
    static_configs:
    - targets: ["peer-29:9119"]

  - job_name: "peer-30"
    static_configs:
    - targets: ["peer-30:9120"]

  - job_name: "peer-31"
    static_configs:
    - targets: ["peer-31:9121"]

  - job_name: "peer-32"
    static_configs:
    - targets: ["peer-32:9122"]

  - job_name: "peer-33"
    static_configs:
    - targets: ["peer-33:9123"]

  - job_name: "peer-34"
    static_configs:
    - targets: ["peer-34:9124"]

  - job_name: "peer-35"
    static_configs:
    - targets: ["peer-35:9125"]

  - job_name: "peer-36"
    static_configs:
    - targets: ["peer-36:9126"]

  - job_name: "peer-37"
    static_configs:
    - targets: ["peer-37:9127"]

  - job_name: "peer-38"
    static_configs:
    - targets: ["peer-38:9128"]

  - job_name: "peer-39"
    static_configs:
    - targets: ["peer-39:9129"]

  - job_name: "peer-40"
    static_configs:
    - targets: ["peer-40:9130"]

  - job_name: "peer-41"
    static_configs:
    - targets: ["peer-41:9131"]

  - job_name: "peer-42"
    static_configs:
    - targets: ["peer-42:9132"]

  - job_name: "peer-43"
    static_configs:
    - targets: ["peer-43:9133"]

  - job_name: "peer-44"
    static_configs:
    - targets: ["peer-44:9134"]

  - job_name: "peer-45"
    static_configs:
    - targets: ["peer-45:9135"]

  - job_name: "peer-46"
    static_configs:
    - targets: ["peer-46:9136"]

  - job_name: "peer-47"
    static_configs:
    - targets: ["peer-47:9137"]

  - job_name: "peer-48"
    static_configs:
    - targets: ["peer-48:9138"]

  - job_name: "peer-49"
    static_configs:
    - targets: ["peer-49:9139"]

  - job_name: "peer-50"
    static_configs:
    - targets: ["peer-50:9140"]
